[package]
name = "graphforge-io"
description = "GraphForge CSV/JSON/Parquet/IPC sinks"
version.workspace = true
edition.workspace = true
license.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
graphforge-core = { version = "0.5.2", path = "../graphforge-core" }
graphforge-storage = { version = "0.5.2", path = "../graphforge-storage" }
thiserror = { workspace = true }

[lints]
workspace = true
