[package]
name = "gf-cli"
description = "GraphForge command-line interface"
version.workspace = true
edition.workspace = true
license.workspace = true
license-file.workspace = true
repository.workspace = true

[[bin]]
name = "gf"
path = "src/main.rs"

[dependencies]
arrow = { workspace = true }
gf-api = { path = "../gf-api" }
clap = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
