#!/usr/bin/env python3
"""Generate checked-in third-party notices from cargo-about JSON."""

from __future__ import annotations

import argparse
from collections import defaultdict
import json
from pathlib import Path
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
ABOUT_CONFIG = ROOT / "about.toml"
OUTPUT = ROOT / "legal" / "THIRD_PARTY_NOTICES.md"
COPIES = (
    ROOT / "crates" / "gf-bindings-py" / "THIRD_PARTY_NOTICES.md",
    ROOT / "crates" / "gf-bindings-node" / "THIRD_PARTY_NOTICES.md",
    ROOT / "crates" / "gf-cli" / "THIRD_PARTY_NOTICES.md",
)
MANIFESTS = (
    ROOT / "crates" / "gf-bindings-py" / "Cargo.toml",
    ROOT / "crates" / "gf-bindings-node" / "Cargo.toml",
    ROOT / "crates" / "gf-cli" / "Cargo.toml",
)


def is_first_party(crate_name: str) -> bool:
    """Return True for GraphForge workspace crates that are not third-party."""
    return crate_name.startswith("gf-") or crate_name == "graphforge"


def _run_cargo_about_once(manifest: Path, json_path: Path) -> dict:
    """Run cargo-about for a single package manifest."""
    cmd = [
        "cargo",
        "about",
        "generate",
        "--format",
        "json",
        "--all-features",
        "--fail",
        "--locked",
        "--offline",
        "--config",
        str(ABOUT_CONFIG),
        "--manifest-path",
        str(manifest),
        "--output-file",
        str(json_path),
    ]
    result = subprocess.run(
        cmd,
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    if result.returncode != 0:
        sys.stderr.write(result.stderr or result.stdout or "cargo about failed\n")
        raise SystemExit(result.returncode)
    if not json_path.exists() or json_path.stat().st_size == 0:
        raise SystemExit(f"cargo about produced empty JSON for {manifest}")
    return json.loads(json_path.read_text(encoding="utf-8"))


def run_cargo_about() -> dict:
    """Collect and merge license JSON for binary redistribution package roots."""
    import tempfile

    merged_licenses: list[dict] = []
    with tempfile.TemporaryDirectory(prefix="gf-about-") as tmp:
        for index, manifest in enumerate(MANIFESTS):
            json_path = Path(tmp) / f"about-{index}.json"
            payload = _run_cargo_about_once(manifest, json_path)
            merged_licenses.extend(payload.get("licenses") or [])
    return {"licenses": merged_licenses}


def render_markdown(data: dict) -> str:
    """Render a stable markdown notice file without HTML escaping."""
    licenses = data.get("licenses") or []

    groups: dict[str, dict] = {}
    overview_counts: dict[str, int] = defaultdict(int)

    for entry in licenses:
        license_id = entry.get("id") or entry.get("name") or "UNKNOWN"
        text = (entry.get("text") or "").replace("\r\n", "\n").replace("\r", "\n")
        used_by = entry.get("used_by") or []

        third_party = []
        for item in used_by:
            if not isinstance(item, dict) or "crate" not in item:
                continue
            crate = item["crate"]
            name = crate.get("name", "")
            version = crate.get("version", "")
            if is_first_party(name):
                continue
            third_party.append((name, version))

        if not third_party:
            continue

        key = f"{license_id}\n{text}"
        group = groups.setdefault(
            key,
            {
                "id": license_id,
                "name": entry.get("name") or license_id,
                "text": text,
                "crates": set(),
            },
        )
        for name, version in third_party:
            if (name, version) not in group["crates"]:
                overview_counts[group["name"]] += 1
            group["crates"].add((name, version))

    lines = [
        "# Third-Party Notices",
        "",
        "This file is generated for GraphForge binary redistributions (Python",
        "wheels, native Node addons, and the CLI). It lists third-party Rust",
        "crates linked into those artifacts and their license texts.",
        "",
        "First-party GraphForge code is licensed under Apache License 2.0",
        "(`Apache-2.0`). See `LICENSE` and `NOTICE`. The openCypher TCK under",
        "`tests/tck/` retains its own Apache License 2.0 files.",
        "",
        "Do not edit this file by hand. Regenerate with:",
        "",
        "```bash",
        "python3 scripts/generate_third_party_notices.py",
        "# or: make third-party-notices",
        "```",
        "",
        "## License overview",
        "",
    ]
    for name, count in sorted(overview_counts.items(), key=lambda item: (-item[1], item[0])):
        lines.append(f"- {name} ({count})")
    lines.append("")

    for group in sorted(groups.values(), key=lambda g: (g["name"], g["text"])):
        lines.extend(
            [
                "--------------------------------------------------------------------------------",
                "",
                f"## {group['name']}",
                "",
                "Used by:",
            ]
        )
        for name, version in sorted(group["crates"]):
            lines.append(f"- {name} {version}")
        lines.extend(["", "```", group["text"].rstrip(), "```", ""])

    return "\n".join(lines).replace("\r\n", "\n").replace("\r", "\n") + "\n"


def write_outputs(text: str) -> None:
    """Write the canonical notice and packaging copies."""
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text, encoding="utf-8")
    for path in COPIES:
        path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(OUTPUT, path)


def check_outputs(text: str) -> list[str]:
    """Return drift errors against checked-in notice copies."""
    errors: list[str] = []
    expected_paths = (OUTPUT, *COPIES)
    for path in expected_paths:
        if not path.exists():
            errors.append(f"{path.relative_to(ROOT)} is missing")
            continue
        if path.read_text(encoding="utf-8") != text:
            errors.append(f"{path.relative_to(ROOT)} is stale; regenerate notices")
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify checked-in notices match a fresh generation without writing",
    )
    args = parser.parse_args(argv)

    data = run_cargo_about()
    text = render_markdown(data)
    if args.check:
        errors = check_outputs(text)
        if errors:
            for error in errors:
                print(f"third-party-notices: {error}", file=sys.stderr)
            return 1
        print("third-party-notices: up to date")
        return 0

    write_outputs(text)
    print(f"wrote {OUTPUT.relative_to(ROOT)} and {len(COPIES)} packaging copies")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
