[package]
name = "gf-search"
description = "GraphForge graph-native text search backend"
version.workspace = true
edition.workspace = true
license.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
arrow = { workspace = true }
gf-storage = { path = "../gf-storage" }
serde = { workspace = true }
serde_json = { workspace = true }
tantivy = { workspace = true }
ureq = { workspace = true }

[dev-dependencies]
gf-core = { path = "../gf-core" }
gf-ir = { path = "../gf-ir" }
tempfile = "3"

[lints]
workspace = true
