"""Tests for the release-specific BUSL policy."""

from datetime import date
import importlib.util
from pathlib import Path
import re

import pytest

SCRIPT = Path(__file__).resolve().parents[2] / "scripts" / "license_policy.py"
SPEC = importlib.util.spec_from_file_location("license_policy", SCRIPT)
assert SPEC and SPEC.loader
license_policy = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(license_policy)


@pytest.mark.parametrize(
    ("released", "changed"),
    [
        (date(2026, 7, 24), date(2029, 7, 24)),
        (date(2024, 2, 29), date(2027, 2, 28)),
        (date(2028, 2, 29), date(2031, 2, 28)),
        (date(2025, 12, 31), date(2028, 12, 31)),
    ],
)
def test_third_anniversary(released: date, changed: date) -> None:
    assert license_policy.third_anniversary(released) == changed


def test_checked_in_policy_is_compliant() -> None:
    policy = license_policy.load_policy()
    assert license_policy.validate_policy(policy) == []


def test_changed_date_is_rejected() -> None:
    policy = license_policy.load_policy()
    policy["change_date"] = "2029-07-23"
    assert "change_date must be 2029-07-24" in license_policy.validate_policy(policy)


def test_missing_render_field_is_reported_without_raising() -> None:
    policy = license_policy.load_policy()
    del policy["commercial_contact"]
    errors = license_policy.validate_policy(policy)
    assert "license policy lacks render fields: commercial_contact" in errors


def test_invalid_release_date_is_rejected_before_writing() -> None:
    with pytest.raises(license_policy.PolicyError, match="invalid release date"):
        license_policy.generate("0.5.0", "2026-02-30")


def test_changed_terms_are_rejected(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    terms = tmp_path / "terms.txt"
    terms.write_text("modified", encoding="utf-8")
    monkeypatch.setattr(license_policy, "TERMS_PATH", terms)
    errors = license_policy.validate_policy(license_policy.load_policy())
    assert "canonical BUSL terms digest does not match" in errors


def test_report_is_sanitized_and_sha_bound() -> None:
    policy = license_policy.load_policy()
    report = license_policy.build_report(policy, [])
    assert report["status"] == "pass"
    assert report["spdx_expression"] == "BUSL-1.1"
    assert report["change_license"] == "AGPL-3.0-only"
    assert re.fullmatch(r"[0-9a-f]{40}", report["git_sha"])
    assert "commercial_contact" not in report
    assert "legal/THIRD_PARTY_NOTICES.md" in report["third_party_notice_copies"]


def test_knowledge_crate_is_covered_by_notice_copies() -> None:
    knowledge_notice = license_policy.ROOT / "crates" / "gf-knowledge" / "NOTICE"
    assert knowledge_notice in license_policy.NOTICE_COPIES
    assert knowledge_notice.exists()
    assert knowledge_notice.read_text(encoding="utf-8") == (
        license_policy.NOTICE_COPIES[0].read_text(encoding="utf-8")
    )


def test_third_party_notice_copies_match() -> None:
    canonical = license_policy.THIRD_PARTY_NOTICE_COPIES[0].read_text(encoding="utf-8")
    assert "Do not edit this file by hand" in canonical
    assert "## Business Source" not in canonical
    for path in license_policy.THIRD_PARTY_NOTICE_COPIES[1:]:
        assert path.read_text(encoding="utf-8") == canonical


def scan_current_doc(monkeypatch: pytest.MonkeyPatch, tmp_path: Path, text: str) -> list[str]:
    """Validate a single synthetic current-line document."""
    doc = tmp_path / "surface.md"
    doc.write_text(text, encoding="utf-8")
    monkeypatch.setattr(license_policy, "CURRENT_DOCS", (doc,))
    return license_policy.validate_policy(license_policy.load_policy())


def test_contributor_surfaces_cover_the_onboarding_path() -> None:
    covered = {path.name for path in license_policy.CURRENT_DOCS}
    assert {"CLA.md", "CODE_OF_CONDUCT.md", "CONTRIBUTING.md", "licensing.md"} <= covered


def test_invalid_boost_style_spdx_identifier_is_rejected(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    errors = scan_current_doc(monkeypatch, tmp_path, "Licensed under BSL-1.1.\n")
    assert any("invalid SPDX identifier BSL-1.1" in error for error in errors)


def test_busl_identifier_is_not_mistaken_for_the_boost_license(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    errors = scan_current_doc(monkeypatch, tmp_path, "Licensed under BUSL-1.1.\n")
    assert not any("invalid SPDX identifier" in error for error in errors)


def test_superseded_repository_identity_is_rejected(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    errors = scan_current_doc(
        monkeypatch, tmp_path, "Clone https://github.com/DecisionNerd/graphforge.git\n"
    )
    assert any("names the superseded repository" in error for error in errors)


def test_repository_manifests_publish_the_canonical_repository() -> None:
    for path in license_policy.REPOSITORY_MANIFESTS:
        text = path.read_text(encoding="utf-8")
        assert license_policy.CANONICAL_REPOSITORY in text
        assert license_policy.SUPERSEDED_REPOSITORY not in text


def test_superseded_repository_in_manifest_is_rejected(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    manifest = tmp_path / "Cargo.toml"
    manifest.write_text('repository = "https://github.com/DecisionNerd/graphforge"\n', "utf-8")
    monkeypatch.setattr(license_policy, "REPOSITORY_MANIFESTS", (manifest,))
    errors = license_policy.validate_policy(license_policy.load_policy())
    assert any("publishes the superseded repository" in error for error in errors)


def test_checked_in_contributor_contract_is_coherent() -> None:
    policy = license_policy.load_policy()
    assert license_policy.validate_contributor_contract(policy) == []


def test_conduct_reports_must_reach_the_recorded_contact(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    conduct = tmp_path / "CODE_OF_CONDUCT.md"
    conduct.write_text(
        "Report to @SomeMaintainer. Adapted from the Contributor Covenant, version 2.1.\n",
        encoding="utf-8",
    )
    monkeypatch.setattr(license_policy, "CODE_OF_CONDUCT_COPIES", (conduct,))
    errors = license_policy.validate_contributor_contract(license_policy.load_policy())
    assert any("does not name the recorded Curate Labs contact" in error for error in errors)


def test_divergent_covenant_versions_are_rejected(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    policy = license_policy.load_policy()
    contact = policy["commercial_contact"]
    copies = []
    for name, version in (("root.md", "2.0"), ("docs.md", "2.1")):
        path = tmp_path / name
        path.write_text(
            f"Report at {contact}.\n\nAdapted from the Contributor Covenant, version {version}.\n",
            encoding="utf-8",
        )
        copies.append(path)
    monkeypatch.setattr(license_policy, "CODE_OF_CONDUCT_COPIES", tuple(copies))
    errors = license_policy.validate_contributor_contract(policy)
    assert any("declare different Contributor Covenant versions: 2.0, 2.1" in e for e in errors)


def test_contributing_must_route_to_every_required_destination(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    contributing = tmp_path / "CONTRIBUTING.md"
    contributing.write_text("Run make pre-push.\n", encoding="utf-8")
    monkeypatch.setattr(license_policy, "CONTRIBUTING_PATH", contributing)
    errors = license_policy.validate_contributor_contract(license_policy.load_policy())
    assert set(license_policy.REQUIRED_CONTRIBUTOR_ROUTES) >= {
        "CLA.md",
        "CODE_OF_CONDUCT.md",
        "docs/legal/licensing.md",
        "SECURITY.md",
    }
    for required in license_policy.REQUIRED_CONTRIBUTOR_ROUTES:
        assert f"CONTRIBUTING.md does not route contributors to {required}" in errors


def test_checked_in_contributing_routes_every_required_destination() -> None:
    text = license_policy.CONTRIBUTING_PATH.read_text(encoding="utf-8")
    for required in license_policy.REQUIRED_CONTRIBUTOR_ROUTES:
        assert required in text


def test_obsolete_covenant_version_is_rejected(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    policy = license_policy.load_policy()
    contact = policy["commercial_contact"]
    copies = []
    for name in ("root.md", "docs.md"):
        path = tmp_path / name
        path.write_text(
            f"Report at {contact}.\n\nAdapted from the Contributor Covenant, version 2.0.\n",
            encoding="utf-8",
        )
        copies.append(path)
    monkeypatch.setattr(license_policy, "CODE_OF_CONDUCT_COPIES", tuple(copies))
    errors = license_policy.validate_contributor_contract(policy)
    # Coherent but obsolete: the divergence check alone would pass this.
    assert not any("declare different Contributor Covenant versions" in error for error in errors)
    assert sum("declares Contributor Covenant version 2.0" in error for error in errors) == 2


def test_checked_in_conduct_copies_adopt_the_required_covenant_version() -> None:
    for path in license_policy.CODE_OF_CONDUCT_COPIES:
        match = license_policy.COVENANT_VERSION_PATTERN.search(path.read_text(encoding="utf-8"))
        assert match is not None
        assert match.group(1) == license_policy.REQUIRED_COVENANT_VERSION


def test_report_records_the_canonical_repository_and_conduct_copies() -> None:
    report = license_policy.build_report(license_policy.load_policy(), [])
    assert report["canonical_repository"] == license_policy.CANONICAL_REPOSITORY
    assert "CODE_OF_CONDUCT.md" in report["code_of_conduct_copies"]
    assert "CLA.md" in report["current_docs"]
    assert license_policy.CANONICAL_REPOSITORY not in report["current_docs"]
