[package]
name = "graphforge-cli"
description = "GraphForge command-line interface"
version.workspace = true
edition.workspace = true
license.workspace = true
license-file.workspace = true
repository.workspace = true

[[bin]]
name = "gf"
path = "src/main.rs"

[dependencies]
arrow = { workspace = true }
graphforge-api = { version = "0.5.2", path = "../graphforge-api" }
graphforge-discovery = { version = "0.5.2", path = "../graphforge-discovery" }
graphforge-storage = { version = "0.5.2", path = "../graphforge-storage" }
clap = { workspace = true }
sha2 = { workspace = true }
tempfile = "3"
ureq = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }

[dev-dependencies]
parquet = { workspace = true }

[lints]
workspace = true
